image: archlinux
sources:
  - https://github.com/mahkoh/jay
tasks:
  - install: |
      sudo pacman -Syu --noconfirm
      sudo pacman -S --noconfirm rustup libinput pango mesa libxkbcommon cmake
      rustup toolchain install stable
  - build: |
      cd jay
      export RUSTC_BOOTSTRAP=1
      cargo build
